version: '3.1'
services:

  backend:
    container_name: environmental-control-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    container_name: environmental-control-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
